export const CHANGE_SEARCH_BAR = "CHANGE_SEARCH_BAR";
export const SAVE_COLLEGE_DATA = "SAVE_COLLEGE_DATA";
//REGISTRATION CONSTANTS
export const REGISTER_EMAIL_NAME_PASS = "REGISTER_EMAIL_NAME_PASS";
export const REGISTER_TIME_SLOT = "REGISTER_TIME_SLOT";
export const REGISTER_DOC_UID = "REGISTER_DOC_UID";
export const REGISTER_COMPLETE = "REGISTER_COMPLETE";
//Login
export const AUTHENTICATION = "AUTHENTICATION";
